### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by nainar**
https://github.com/ampproject/wg-codeofconduct/issues/6

### CODE REVIEW

**Comment by nainar** [comment]
@danielrozenberg can I get a review please?

**Comment by estherkim** [comment]
@nainar This repo is read-only.

**Comment by nainar** [comment]
@estherkim closing this issue in that case but let's mark the repo as such?

**Comment by danielrozenberg** [comment]
I think it's still fine to have this here, somebody might want to add modify README.md :)

**Pull request merged**
